# Generated by Django 4.2.2 on 2024-07-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0002_homecategory_homeproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeProduct',
            new_name='Refrigreator',
        ),
    ]
