# Generated by Django 4.2.2 on 2024-07-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0003_rename_homeproduct_refrigreator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refrigreator',
            new_name='HomeProduct',
        ),
    ]
