# Generated by Django 4.2.2 on 2024-07-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0004_rename_refrigreator_homeproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeCategory',
            new_name='SubCategory',
        ),
        migrations.RenameModel(
            old_name='HomeProduct',
            new_name='SubProduct',
        ),
    ]
