# Generated by Django 4.2.2 on 2024-07-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0005_rename_homecategory_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='original_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/upload'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='small_description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tag',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='SubProduct',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.category1'),
        ),
    ]
