# Generated by Django 4.2.2 on 2024-07-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0006_category1_subcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category1',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/upload'),
        ),
    ]
