# Generated by Django 4.2.2 on 2024-07-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0007_category1_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
