# Generated by Django 4.2.2 on 2024-07-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0008_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrival',
            old_name='product_image',
            new_name='image',
        ),
    ]
