# Generated by Django 4.2.2 on 2024-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0009_rename_product_image_arrival_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('MRP', models.FloatField(null=True)),
                ('SP', models.FloatField(blank=True, null=True)),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
