# Generated by Django 4.2.2 on 2024-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0010_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='MRP',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='arrival',
            name='SP',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
