# Generated by Django 4.2.2 on 2024-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0011_arrival_mrp_arrival_sp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='MRP',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='SP',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
