# Generated by Django 4.2.2 on 2024-07-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0015_alter_reviews_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=200)),
                ('Business', models.CharField(max_length=200)),
                ('Service', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
