# Generated by Django 4.2.2 on 2024-07-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0016_contact_delete_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Business',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Service',
        ),
    ]
