# Generated by Django 4.2.2 on 2024-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0017_remove_contact_business_remove_contact_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=200)),
                ('Product', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
    ]
