# Generated by Django 4.2.2 on 2024-07-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0018_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Email',
            new_name='Email2',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Message',
            new_name='Message2',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Name',
            new_name='Name2',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Phone',
            new_name='Phone2',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Product',
            new_name='Product2',
        ),
    ]
