# Generated by Django 4.2.2 on 2024-07-26 14:09

import Ecomapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0020_alter_feedback_product2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name3', models.CharField(max_length=200)),
                ('Email3', models.EmailField(max_length=254)),
                ('Phone3', models.CharField(max_length=200)),
                ('Product3', models.CharField(max_length=200)),
                ('Model3', models.CharField(max_length=200)),
                ('Uploadbill3', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('Message3', models.TextField()),
            ],
        ),
    ]
