# Generated by Django 4.2.2 on 2024-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0021_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
