# Generated by Django 4.2.2 on 2024-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0022_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
