# Generated by Django 4.2.2 on 2024-08-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0026_order_alter_cart_product_qty_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Quantity',
            field=models.IntegerField(default=False),
        ),
    ]
