# Generated by Django 4.2.2 on 2024-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0028_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Productimg',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/upload'),
        ),
    ]
