# Generated by Django 4.2.2 on 2024-11-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0030_photo_video_vidio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
