# Generated by Django 4.2.2 on 2024-11-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0031_remove_video_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vidio',
        ),
    ]
