# Generated by Django 4.2.2 on 2024-11-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0033_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
