# Generated by Django 4.2.2 on 2024-11-15 07:02

import Ecomapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0036_rename_image_brands_logo_brands_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=1200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='Logo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='name',
        ),
    ]
