# Generated by Django 4.2.2 on 2024-11-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0040_remove_orderitem_productimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payment_Id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='Country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='Fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='Lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='Pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
