# Generated by Django 4.2.2 on 2024-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0041_rename_created_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/blog_images/')),
                ('heading', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1800)),
            ],
        ),
    ]
