# Generated by Django 4.2.2 on 2024-11-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0042_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
